### PR TITLE
Upgraded to Ruby 2.2.4; Fixed 2 links in README file

### PR DESCRIPTION
**Pull request by jasnow**
* Upgraded to Ruby 2.2.4.
 * Fixed 2 links in README file
 * Added 1 line to set up instructions to remind about exiftool.
 * Added 3 lines to .gitignore file to not force others to use my conventions.

### CODE REVIEW

**Comment by jasnow** [comment]
FYI: working the broken Travis build

**Comment by henrylawson** [comment]
Thanks mate, really appreciate the help!

**Comment by jasnow** [comment]
want Ruby 2.3.0 upgrade?

**Comment by henrylawson** [comment]
Thanks for the offer, it has prompted me to setup multiple ruby builds for all the versions i'd like to support. 

I also realised that I lost 1.9.x compatibility with the mime-types gem. I'll add that to the todo list to look at later. Thanks for your pull request, keep them coming!

**Pull request merged**
